### ISSUE TITLE
[angular-cli-hooks] Feature request: Support for ng-packagr

### ISSUE THREAD

**Issue by fidian** [blidblid/berglund#3]
I would like to tie custom hooks into ng-packagr when I build a library that's shared across multiple Angular projects. Is this feasible?

**Comment by blidblid** [comment]
Have you tried adding hook to `build-lib`?

```
hook({
    name: 'build-lib',
    before: async (): Promise<BuilderOutput> => {
      return { success: true };
    },
  });
```

**Comment by fidian** [comment]
No, sorry. I didn't know what hook to use and tried `ng-packagr`. I don't know where to look up hook names and when they get applied.

Using `build-lib` worked for me. Thanks!
