### ISSUE TITLE
[angular-cli-hooks] Schema doesn't get applied

### ISSUE THREAD

**Issue by fidian** [blidblid/berglund#6]
Using angular-cli-hooks 0.0.6 and Angular 13.

Error message:
```
$ npx ng build
Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(fakeSetting).
```

And some code:
```
const hooks = [
    hook({
        name: 'build',
        schema: {
            properties: {
                fakeSetting: {
                    type: 'boolean'
                }
            }
        },
        before: runAtomizer,
    }),
];
```

What do I have wrong?

**Comment by fidian** [comment]
I've uninstalled `@berglund/angular-cli-hooks` and reinstalled it and now it works. Really weird.

To test a theory, I modified my hook package, which is linked into my Angular app repository, which means there is a symlink under `node_modules` pointing to my hooks code. I updated the schema to change the name of the option from `fakeSetting` to `fakeSetting2` but did not change `fakeSetting` in `angular.json`. `ng build` works. Next, I changed `fakeSetting` to `fakeSetting2` in `angular.json` and `ng build` now fails.

Do you do something special to make schemas work? If so, that would be a wonderful thing to document in README - something along the lines of "you need to `npm install` any updates to your package or reinstall this module so ...(action happens)..."

**Comment by blidblid** [comment]
Right, it's just poor documentation on my part.

The schemas in your hooks package are merged with the Angular schemas in the `postinstall` hook. If you reinstall, the merging will happen. I'll fix the docs and close this issue.

**Comment by blidblid** [comment]
I updated the docs.
